name = "Matcha's MTR"
author = "AwesomeKalin55, matcha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84131291da4c0fed89abfc38b164a9210ba81be6a566f46ec8bb86d855d49be2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
