name = "Matcha's MTR"
author = "AwesomeKalin55, matcha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e660073eab3be2d7524c5d0a820c6a934b0c74b5c8038ce98031c9a6a33068"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
